services:
  - type: web
    name: gates-tracker-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gates_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gates_tracker_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health-check/
